### ISSUE TITLE
beam-sdks-java-io-jdbc 2.5.0 not working 

### ISSUE THREAD

**Issue by gyamxxx** [olavloite/spanner-beam-example#1]
Hi, I'm sorry for my poor English.
Apache beam 2.5.0 was released, but this example doesn't work at beam-sdks-java-io-jdbc 2.5.0 on DataflowRunner. 
 - DirectRunner works.
 - There are no error logs.
![hchistorycheck_20180712 dataflow gcp kpi](https://user-images.githubusercontent.com/6592208/42795671-8eab7fbc-89c0-11e8-9625-7e5813cab047.png)

**Comment by olavloite** [comment]
The example project has been updated and now uses Apache Beam 2.5.0. It runs on both the DirectRunner and the DataflowRunner. Note that this version now uses version 1.0.13 of the JDBC driver, as that version supports using a authentication key file stored in Google Cloud Storage instead of only local files.
The example configuration uses a Google Cloud Spanner emulator. You should supply your own JDBC URL configuration to point to your own Cloud Spanner instance of emulator instance.
